tls:
  certificates:
    - certFile: /etc/traefik/certs/cert.pem
      keyFile: /etc/traefik/certs/key.pem
      stores:
        - default

  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/cert.pem
        keyFile: /etc/traefik/certs/key.pem

http:
  middlewares:
    static-cache:
      headers:
        customResponseHeaders:
          Cache-Control: "public, max-age=31536000, immutable"
          X-Served-By: "Traefik-Static-Cache"
    gzip-compress:
      compress: {}
