server {
    listen 80;
    server_name _;

    location /uploads/ {
        alias /var/www/uploads/;
        autoindex off;
        expires 365d;
        add_header Cache-Control "public, max-age=31536000, immutable";
        add_header X-Served-By "Traefik-Static-Cache";
        try_files $uri =404;
    }
}
